- minor alignments to cst-git; no binary changes

diff --git a/src/gui/Makefile.am b/src/gui/Makefile.am
--- a/src/gui/Makefile.am
+++ b/src/gui/Makefile.am
@@ -8,7 +8,7 @@ version.h:
 		pushd $(top_srcdir) ; \
 		GITTAG=$$(git tag -l "NI-*" | tail -n1); \
 		GITBRANCH=$$(git rev-parse --abbrev-ref HEAD) ; \
-		GITDESCRIBE=$$(git describe --always --dirty --tags --match $$GITTAG || echo 'VCS failed') ; \
+		GITDESCRIBE=$$(git describe --always --tags --dirty --match $$GITTAG || echo 'VCS failed') ; \
 		popd ; \
 		echo '#define VCS "'$${GITDESCRIBE} [$${GITBRANCH}]'"' >> $@ ; \
 	fi
